import {displayDate} from './date-format.mjs';
import React from 'react';
import {Section,DataComponent,DataTable,MetricCard} from '../../data-app-public.jsx';
import {rankedPeriods,dailyPeaks,organizationCounts} from './metrics.mjs';
export function ActivityInsights({rows,days}){
 const topDays=rankedPeriods(rows,'day',10),topMonths=rankedPeriods(rows,'month'),peaks=dailyPeaks(rows,days);
 const metric=(id,title,ranked)=><MetricCard id={id} queryId="emails" title={title} value={ranked[0]?.emails??0} displayRows={ranked.filter(r=>r.rank===1)} sourceRows={rows}><span className="hint">{ranked.length?ranked.filter(r=>r.rank===1).map(r=>displayDate(r.period)).join(', ')+' · emails per period':'No matching emails'}</span></MetricCard>;
 const table=(id,title,data,columns)=><DataComponent id={id} queryId="emails" title={title} kind="table" variant="card" displayRows={data} sourceRows={rows}><DataTable rows={data} columns={columns.map(([key,label])=>({key,label,renderCell:['period','day'].includes(key)?displayDate:undefined}))} label={title}/></DataComponent>;
 return <Section id="activity-insights" title="Busiest dates and daily peak hours"><p className="intro">Rankings follow all current filters. Choose All dates or Last 3 months in export in the calendar to compare months. Counts cover this export; April and August have partial coverage.</p><div className="time-grid">{metric('busiest-day','Top day: email count',topDays)}{metric('busiest-month','Top month: email count',topMonths)}</div><div className="time-grid">
 {table('top-days','Top 10 days (including ties)',topDays,[['rank','Rank'],['period','Date'],['emails','Emails']])}
 {table('top-months','Months ranked by email count',topMonths,[['rank','Rank'],['period','Month'],['emails','Emails']])}</div>
 <p className="hint">Peak windows are fixed clock hours, e.g. 09:00-10:00. Every tied window is listed; the peak count is for each window, not their sum. Days without matching messages show No emails. Recorded timezone is unspecified.</p>
 {table('daily-peaks','Peak one-hour window for every day',peaks,[['day','Date'],['windows','Peak window(s)'],['peak','Emails per peak window'],['total','Daily emails'],['tiedWindows','Tied windows']])}</Section>;
}
export function Organizations({rows,country,region,city}){
 const orgs=organizationCounts(rows),location=[country,region,city].filter(s=>s!=='all').join(' / ')||'All locations';
 return <Section id="location-organizations" title="Organizations in the selected location"><p className="intro" aria-live="polite">{location} · {orgs.filter(r=>r.organization&&r.organization!=='Organization not identified').length} organization labels (including assumptions). Organization names refer to the conversation contact; both sent and received emails contribute to the counts.</p><DataComponent id="organization-list" queryId="emails" title="Organization names and activity" kind="table" variant="card" displayRows={orgs} sourceRows={rows}><DataTable rows={orgs} label="Organizations in selected location" columns={[['organization','Organization'],['emails','Emails'],['conversations','Conversations'],['cities','City'],['regions','Region'],['countries','Country'],['contacts','Contact email'],['names','Contact name (assumed)']].map(([key,label])=>({key,label,renderCell:key==='organization'?value=><span>{value||''}</span>:undefined}))}/></DataComponent><p className="hint">Country, region and city bar selections update this list. Missing organization names use the contact email domain, marked assumed and kept separate by mailbox. Names before @ are assumed contact names. Company names inferred from personal email providers (such as Gmail, Outlook, Yahoo and iCloud) are left blank. The Turtle Down Under location label is reserved for internal-only threads. External contacts without a known address remain Unknown.</p></Section>;
}
